### ISSUE TITLE
How does re2fa work?

### ISSUE THREAD

**Issue by OrangieLou** [d06alexandrov/re2fa#15]
Hi @d06alexandrov,

I just tried to make your converter work and have a few questions:

1. Could you explain the output?
I ran your example command but don't understand the output. I was expecting a table or something else representing the dfa. What are cnt and bps? Where are the states and relation for state changes?
```sh 
❯ ./re2fa --input-type=regexp -v -m '/a.{4}c/is'
dfa minimized 33->33
[dfa]
  state cnt: 33, bps: 64
```

2. What does my `regexp.file` have to look like for this `./re2fa --input-type=regexp-file -v -m regexp.file -o result.dfa` to work? Could you provide an example? I constantly get "wrong syntax" errors.

3.  What do the 'm', 's' and 'i' modifiers mean/do?

Thanks in advance!

_____________________________________________________________________________________________________________
PS: These were the commands I had to run to be able to run the building commands. Maybe you'd like to include them in your Readme. :)

```sh
brew install autoconf automake libtool
brew install argp-standalone

# get path where argp-standalone is installed:
brew info argp-standalone

# add this to your .zshrc (change path to argp-standalone if necessary)
export LDFLAGS="$LDFLAGS -L/opt/homebrew/Cellar/argp-standalone/1.3/lib/ -largp"
export CFLAGS="$CFLAGS -I/opt/homebrew/Cellar/argp-standalone/1.3/include/"

source ~/.zshrc
```

**Comment by d06alexandrov** [comment]
Hi @OrangieLou,

Thank you for your interest in this project.
It is under heavy refactoring now, so some features are simply not available now.

1. This not very fancy output shows that minimized DFA for the corresponding regular expression has 33 states.

There is already implemented but not yet provided function to print DFA in [Graphviz](https://graphviz.org/) format.
I was planning to do it this week.

2. There is a bug. Application should work with files with something like:

```
/a.{4}c/is
/b.{4}d/is

```
3. It's basic [PCRE modifiers](https://perldoc.perl.org/perlre#Modifiers).

- i : Matches both uppercase and lowercase letters.
- m : Matches across multiple lines.
- s : A dot metacharacter in the pattern matches a character of any value, including one that indicates a newline.

**Comment by d06alexandrov** [comment]
Added a preview version of Graphviz output.
Here is an example of generating a transition graph in png format using the `dot` util from the Graphviz packet.

```
> ./re2fa --input-type=regexp -g -m "/a.{2}c/s" > dfa.gv
> dot -O -Tpng dfa.gv
```

However, when you have more than 10-20 states, the transition graph usually becomes a bit messy. So rendering it is a bit useless in such case.

**Comment by OrangieLou** [comment]
Thanks @d06alexandrov,

the graph output works. 🎉

So just a followup question:
If I try a very simple pattern like `/a{2}c+/` this should match only strings that start with _aac_ followed by an arbitrary number of _c_'s, e.g. _aac, aacccccc, aaccccccccccc_.
However, the graph looks like this:
![dfa gv](https://github.com/d06alexandrov/re2fa/assets/15362802/64cbe3c6-7d93-431f-994d-c55f341c275f)
the label for the recursive arrow at state 1 is `0x00-xFF` but shouldn't it be `c`?
Also, there is a recursive label for `a` on state 2 that should not be there. {2} means exactly two occurrences, not two+ afaik. See https://techbyexample.com/curly-braces-quantifier-regex/ . 

I am not sure about any of the negating ^ connections. This way it looks like the string baac could be a match. Shouldn't all other characters lead to a dead end (non-accepting state).

I ran the regex with the commands you pointed me to:
`./re2fa --input-type=regexp -g -m "/a{2}c+/" -o dfa.gv`

**Comment by d06alexandrov** [comment]
Without metacharacters ^ and $ regular expression `"/a{2}c+/"` matches all strings with a substring `aac`.

It seems that you need something like `"/^a{2}c+$/"`.
![dfa gv](https://github.com/d06alexandrov/re2fa/assets/11277743/9c422ad3-c740-44f7-b86f-40c6b9a707de)

**Comment by OrangieLou** [comment]
I see, yes, sorry, I was thinking of full matches only. That makes sense. Thanks!
